# Generated by Django 4.0.3 on 2022-03-30 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Фио врача')),
                ('spec', models.CharField(choices=[('дерматолог-косметолог', 'дерматолог-косметолог'), ('пластический хирург', 'пластический хирург'), ('Администратор', 'Администратор'), ('Другое', 'Другое'), ('Гл.врач', 'Гл.врач')], max_length=250, verbose_name='Специальность')),
                ('phone', models.CharField(blank=True, max_length=250, null=True, verbose_name='Телефон')),
                ('email', models.CharField(blank=True, max_length=250, null=True, verbose_name='Email')),
                ('category_account', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=12, verbose_name='Account Cat')),
                ('category_restylane', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], max_length=12, verbose_name='Restylane loyalty')),
                ('category_sculptra', models.CharField(choices=[('L-D', 'L-D'), ('LOW', 'LOW'), ('MID', 'MID'), ('TOP', 'TOP')], max_length=12, verbose_name='Sculptra Cat')),
                ('city', models.CharField(max_length=250, verbose_name='Город')),
                ('work_place', models.CharField(max_length=250, verbose_name='Место работы')),
                ('comment', models.CharField(blank=True, max_length=250, null=True, verbose_name='Комментарий')),
                ('name_dashboard', models.CharField(blank=True, max_length=250, null=True, verbose_name='Наименование в DB')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Kam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Фио сотрудника')),
                ('siteuser', models.CharField(max_length=250, verbose_name='Логин на сайте')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Vizit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viztype', models.CharField(choices=[('К специалисту', 'К специалисту'), ('Follow-up визит', 'Follow-up визит'), ('Телефонный визит', 'Телефонный визит')], max_length=20, verbose_name='Тип визита')),
                ('datenext', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата следующего визита')),
                ('datefact', models.DateTimeField(db_index=True, verbose_name='Дата визита')),
                ('goal', models.CharField(db_index=True, max_length=200, verbose_name='Цель визита')),
                ('nextaction', models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Дальнейшие действия с клиентом')),
                ('social_link', models.BooleanField(blank=True, null=True, verbose_name='Подписание клиента на соцсети')),
                ('result', models.CharField(blank=True, choices=[('Cold', 'Cold'), ('Warm', 'Warm'), ('Hot', 'Hot')], max_length=10, verbose_name='Результат визита (личная оценка)')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('hint_organization', models.CharField(blank=True, db_index=True, max_length=200, null=True, verbose_name='Место работы')),
                ('hint_special', models.CharField(blank=True, db_index=True, max_length=200, null=True, verbose_name='Специальность')),
                ('datecreate', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='vizit.contact', verbose_name='Контакт')),
                ('kamid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vizit.kam', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Визит',
                'verbose_name_plural': 'Визиты',
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='kam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='vizit.kam', verbose_name='КАМ'),
        ),
    ]
