# Generated by Django 4.0.3 on 2022-04-05 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vizit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vizit',
            name='vizstatus',
            field=models.CharField(choices=[('Открыт', 'Открыт'), ('Закрыт', 'Закрыт')], default='Открыт', max_length=20, verbose_name='Статус'),
        ),
    ]
