# Generated by Django 4.0.3 on 2022-04-21 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vizit', '0003_alter_vizit_nextaction_alter_vizit_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='VizitFreq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('month', models.IntegerField(verbose_name='Месяц')),
                ('workdays', models.IntegerField(verbose_name='Колво рабочих дней в месяце')),
                ('dayoff_minus', models.IntegerField(verbose_name='Колво выходных у сотрудника')),
                ('dayadm_minus', models.FloatField(verbose_name='Колво дней административной работы')),
                ('workday_count', models.IntegerField(verbose_name='Колво рабочих дней')),
                ('contact_count_a', models.IntegerField(verbose_name='Колво врачей А')),
                ('contact_count_b', models.IntegerField(verbose_name='Колво врачей B')),
                ('contact_count_c', models.IntegerField(verbose_name='Колво врачей C')),
                ('plan_count_a', models.IntegerField(verbose_name='План визитов А')),
                ('plan_count_b', models.IntegerField(verbose_name='План визитов B')),
                ('plan_count_c', models.IntegerField(verbose_name='План визитов C')),
                ('kamid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='vizit.kam', verbose_name='КАМ')),
            ],
        ),
    ]
