# Generated by Django 4.0.3 on 2022-04-22 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vizit', '0004_vizitfreq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vizitfreq',
            name='contact_count_a',
            field=models.IntegerField(blank=True, null=True, verbose_name='Колво врачей А'),
        ),
        migrations.AlterField(
            model_name='vizitfreq',
            name='contact_count_b',
            field=models.IntegerField(blank=True, null=True, verbose_name='Колво врачей B'),
        ),
        migrations.AlterField(
            model_name='vizitfreq',
            name='contact_count_c',
            field=models.IntegerField(blank=True, null=True, verbose_name='Колво врачей C'),
        ),
        migrations.AlterField(
            model_name='vizitfreq',
            name='plan_count_a',
            field=models.IntegerField(blank=True, null=True, verbose_name='План визитов А'),
        ),
        migrations.AlterField(
            model_name='vizitfreq',
            name='plan_count_b',
            field=models.IntegerField(blank=True, null=True, verbose_name='План визитов B'),
        ),
        migrations.AlterField(
            model_name='vizitfreq',
            name='plan_count_c',
            field=models.IntegerField(blank=True, null=True, verbose_name='План визитов C'),
        ),
        migrations.AlterField(
            model_name='vizitfreq',
            name='workday_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Колво рабочих дней'),
        ),
    ]
