# Generated by Django 4.0.3 on 2022-04-22 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vizit', '0006_alter_vizitfreq_dayadm_minus_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vizitfreq',
            options={'verbose_name': 'Частота визитов', 'verbose_name_plural': 'Частота визитов'},
        ),
        migrations.AddField(
            model_name='vizitfreq',
            name='freq_a',
            field=models.FloatField(blank=True, null=True, verbose_name='Частота А'),
        ),
        migrations.AddField(
            model_name='vizitfreq',
            name='freq_b',
            field=models.FloatField(blank=True, null=True, verbose_name='Частота B'),
        ),
        migrations.AddField(
            model_name='vizitfreq',
            name='freq_c',
            field=models.FloatField(blank=True, null=True, verbose_name='Частота C'),
        ),
        migrations.AlterField(
            model_name='vizitfreq',
            name='dayadm_minus',
            field=models.FloatField(blank=True, null=True, verbose_name='Адм. работа'),
        ),
        migrations.AlterField(
            model_name='vizitfreq',
            name='dayoff_minus',
            field=models.IntegerField(blank=True, null=True, verbose_name='Выходные'),
        ),
        migrations.AlterField(
            model_name='vizitfreq',
            name='workday_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Итого дней работы'),
        ),
        migrations.AlterField(
            model_name='vizitfreq',
            name='workdays',
            field=models.IntegerField(blank=True, null=True, verbose_name='Дней в месяце'),
        ),
    ]
