# Generated by Django 4.0.3 on 2022-04-25 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vizit', '0007_alter_vizitfreq_options_vizitfreq_freq_a_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vizitfreq',
            name='freq_total',
            field=models.FloatField(blank=True, null=True, verbose_name='Частота C'),
        ),
    ]
