# Generated by Django 4.0.3 on 2022-04-25 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vizit', '0008_vizitfreq_freq_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='vizitfreq',
            name='kamname',
            field=models.CharField(default=0, max_length=250, verbose_name='Фио kam'),
            preserve_default=False,
        ),
    ]
