# Generated by Django 4.0.3 on 2022-04-25 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vizit', '0009_vizitfreq_kamname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vizitfreq',
            name='kamname',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Фио kam'),
        ),
    ]
