# Generated by Django 4.0.3 on 2022-04-25 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vizit', '0010_alter_vizitfreq_kamname'),
    ]

    operations = [
        migrations.AddField(
            model_name='vizitfreq',
            name='fact_count_a',
            field=models.IntegerField(blank=True, null=True, verbose_name='Факт визитов А'),
        ),
        migrations.AddField(
            model_name='vizitfreq',
            name='fact_count_b',
            field=models.IntegerField(blank=True, null=True, verbose_name='Факт визитов B'),
        ),
        migrations.AddField(
            model_name='vizitfreq',
            name='fact_count_c',
            field=models.IntegerField(blank=True, null=True, verbose_name='Факт визитов C'),
        ),
        migrations.AddField(
            model_name='vizitfreq',
            name='procent_a',
            field=models.FloatField(blank=True, null=True, verbose_name='% А'),
        ),
        migrations.AddField(
            model_name='vizitfreq',
            name='procent_b',
            field=models.FloatField(blank=True, null=True, verbose_name='% B'),
        ),
        migrations.AddField(
            model_name='vizitfreq',
            name='procent_c',
            field=models.FloatField(blank=True, null=True, verbose_name='% C'),
        ),
    ]
