# Generated by Django 4.0.3 on 2022-04-25 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vizit', '0011_vizitfreq_fact_count_a_vizitfreq_fact_count_b_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vizitfreq',
            name='workday_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Дней работы'),
        ),
    ]
