# Generated by Django 4.0.3 on 2022-04-28 10:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vizit', '0013_alter_vizitfreq_workday_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
    ]
