# Generated by Django 4.0.3 on 2022-05-24 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vizit', '0015_event_eventmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topicname', models.CharField(db_index=True, max_length=200, verbose_name='Тема мероприятия')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='kamid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='vizit.kam', verbose_name='Сотрудник'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventmember',
            name='grade',
            field=models.CharField(db_index=True, default=1, max_length=200, verbose_name='Оценка'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='goal',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Цель'),
        ),
        migrations.AddField(
            model_name='event',
            name='topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='vizit.eventtopic', verbose_name='Тема мероприятия'),
            preserve_default=False,
        ),
    ]
