# Generated by Django 4.0.3 on 2022-05-24 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vizit', '0016_eventtopic_event_kamid_eventmember_grade_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventtopic',
            options={'verbose_name': 'Темы мероприятий', 'verbose_name_plural': 'Тема мероприятия'},
        ),
        migrations.RemoveField(
            model_name='eventmember',
            name='grade',
        ),
    ]
