# Generated by Django 4.0.3 on 2022-05-24 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vizit', '0017_alter_eventtopic_options_remove_eventmember_grade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Мероприятия', 'verbose_name_plural': 'Мероприятие'},
        ),
        migrations.AddField(
            model_name='event',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Город'),
        ),
    ]
