# Generated by Django 4.0.4 on 2022-06-27 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vizit', '0018_alter_event_options_event_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='date',
            new_name='dateevent',
        ),
    ]
