# Generated by Django 4.0.4 on 2022-10-04 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vizit', '0019_rename_date_event_dateevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='cat_biostim_loyalty',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], max_length=12, null=True, verbose_name='Biostimulators Loyalty'),
        ),
        migrations.AddField(
            model_name='contact',
            name='cat_biostim_potencial',
            field=models.CharField(blank=True, choices=[('LD', 'LD'), ('LOW', 'LOW'), ('MID', 'MID'), ('TOP', 'TOP')], max_length=12, null=True, verbose_name='Biostimulators Category Potential'),
        ),
        migrations.AddField(
            model_name='contact',
            name='cat_filler_loyalty',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], max_length=12, null=True, verbose_name='Fillers Loyalty'),
        ),
        migrations.AddField(
            model_name='contact',
            name='cat_filler_potencial',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=12, null=True, verbose_name='Fillers Category Potencial'),
        ),
        migrations.AddField(
            model_name='contact',
            name='cat_idp_loyalty',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], max_length=12, null=True, verbose_name='IDP Loyalty'),
        ),
        migrations.AddField(
            model_name='contact',
            name='cat_idp_potencial',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=12, null=True, verbose_name='IDP Category'),
        ),
    ]
