# Generated by Django 4.0.4 on 2022-10-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vizit', '0020_contact_cat_biostim_loyalty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='category_account',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=12, null=True, verbose_name='Account Cat'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='category_restylane',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], max_length=12, null=True, verbose_name='Restylane loyalty'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='category_sculptra',
            field=models.CharField(blank=True, choices=[('L-D', 'L-D'), ('LOW', 'LOW'), ('MID', 'MID'), ('TOP', 'TOP')], max_length=12, null=True, verbose_name='Sculptra Cat'),
        ),
    ]
