# Generated by Django 4.0.4 on 2023-01-27 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vizit', '0021_alter_contact_category_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
