# Generated by Django 4.0.4 on 2023-01-27 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vizit', '0022_contact_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Контакт удален'),
        ),
    ]
